### PR TITLE
Add Color interface

### PR DESCRIPTION
**Pull request by psincraian**
I would like to be able to specify my own colors, this can be possible by adding an interface and using it everywhere in BadgeFormat, BadgeFormatBuilder, etc.

Let me know if this works for you.

### CODE REVIEW

**Review by dsibilio — CHANGES_REQUESTED** [review]
Thank you for your first contribution! I think that's a great idea, and the approach is completely fine. Just one minor suggestion before I merge this in and give a go at releasing a new version of this library, could you please rename the `Color` interface to `HexColor` instead? I don't want it to collide with `java.awt.Color`, potentially forcing users to declare the full namespace of one or the other in case they need to import both 🙏

**Comment by psincraian** [comment]
Agree! I just changed it :)

**Review by dsibilio — APPROVED** [review]
LGTM. Thanks again!

**Comment by dsibilio** [comment]
The `1.0.4` release should now be available on Maven Central: https://repo1.maven.org/maven2/io/github/dsibilio/badge-maker/1.0.4/.

**Pull request merged**
